name: CI/CD with Terraform
on:
  push:
    branches:
         - Complete-CI/CD-with-Terraform-AWS
env: 
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
   TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_BUCKET_NAME }}
   PRIVATE_SSH_KEY: ${{secrets.AWS_SSH_KEY_PRIVATE}}
   PUBLIC_SSH_KEY: ${{secrets.AWS_SSH_KEY_PUBLIC}}
   AWS_REGION: ap-south-1

jobs:
    deploy-infra:
       runs-on: ubuntu-latest
       steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
             teraaform_wrappers: false
        - name: Terraform init
          id: init 
          run:  terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=ap-south-1"  
          working-directory: './terraform'
        - name: Terraform Plan
          id: plan
          run: |-
            terraform plan \
            -var="region=us-east-1" \
            -var="public_key=$PUBLIC_SSH_KEY" \
            -var="private_key=$PRIVATE_SSH_KEY" \
            -var="key_name=deployer-key" \
            -out=PLAN
          working-directory: './terraform'
        - name: Terraform Apply
          id: apply 
          run: terraform apply PLAN
          working-directory: './terraform' 
