name: CI/CD Terraform on AWS
on:
  push:
    branches:
      - Complete-CI/CD-with-Terraform-AWS

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_SECRET_KEY}}
  TF_STATE_BUCKET_NAME: ${{secrets.AWS_TF_BUCKET_NAME}}
  PRIVATE_SSH_KEY: ${{secrets.AWS_SSH_KEY_PRIVATE}}
  PUBLIC_SSH_KEY : ${{secrets.AWS_SSH_KEY_PUBLIC}}
  AWS_REGION: ap-south-1

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    outputs:
      SERVER_PUBLIC_IP: ${{ steps.set-ip.outputs.instance_public_ip}}
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=ap-south-1"
        working-directory: ./terraform
      - name: Terraform destroy
        id: destroy
        run: |
          terraform destroy -auto-approve \
          -var="region=ap-south-1" \
          -var="public_key=$PUBLIC_SSH_KEY" \
          -var="private_key=$PRIVATE_SSH_KEY" \
          -var="key_name=deployer-key" \
        working-directory: ./terraform